# Generated by Django 5.2.7 on 2025-11-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("heading", models.CharField(max_length=150, verbose_name="Заголовок")),
                ("text", models.TextField(verbose_name="Текст")),
                ("preview", models.ImageField(null=True, upload_to="images/", verbose_name="Превью")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("is_publicated", models.BooleanField(default=True, verbose_name="Признак публикации")),
                ("views_counter", models.IntegerField(default=0, verbose_name="Счетчик просмотров")),
            ],
            options={
                "verbose_name": "публикация",
                "verbose_name_plural": "публикации",
                "db_table": "publications",
                "ordering": ["created_at"],
            },
        ),
    ]
