# Generated by Django 5.2.7 on 2025-11-03 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category_name", models.CharField(max_length=150, verbose_name="Наименование")),
                ("description", models.TextField(max_length=150, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
                "db_table": "categories",
                "ordering": ["category_name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_name", models.CharField(max_length=150, verbose_name="Наименование")),
                ("description", models.TextField(null=True, verbose_name="Описание")),
                ("image", models.ImageField(null=True, upload_to="images/", verbose_name="Изображение")),
                ("price", models.FloatField(verbose_name="Цена")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата последнего изменения")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
                "db_table": "products",
                "ordering": ["product_name"],
            },
        ),
    ]
